// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcGJkOVMpNJ4O-4g2JjSmtao9BUFhwLS8',
    appId: '1:594367967534:web:5a71c3096ecc6db1794abf',
    messagingSenderId: '594367967534',
    projectId: 'growing-beans-edu-tjwns',
    authDomain: 'growing-beans-edu-tjwns.firebaseapp.com',
    storageBucket: 'growing-beans-edu-tjwns.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFcRO1H74qB5T2nivekdnfAIJ2mJETh90',
    appId: '1:594367967534:android:5978234e62cc2cfe794abf',
    messagingSenderId: '594367967534',
    projectId: 'growing-beans-edu-tjwns',
    storageBucket: 'growing-beans-edu-tjwns.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCunDz5JE373Sd-vRWfETa7LYk1L4-ZbLc',
    appId: '1:594367967534:ios:3dc57f37dc1e0b8d794abf',
    messagingSenderId: '594367967534',
    projectId: 'growing-beans-edu-tjwns',
    storageBucket: 'growing-beans-edu-tjwns.firebasestorage.app',
    iosBundleId: 'com.growingbeans.growingBeans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCunDz5JE373Sd-vRWfETa7LYk1L4-ZbLc',
    appId: '1:594367967534:ios:3dc57f37dc1e0b8d794abf',
    messagingSenderId: '594367967534',
    projectId: 'growing-beans-edu-tjwns',
    storageBucket: 'growing-beans-edu-tjwns.firebasestorage.app',
    iosBundleId: 'com.growingbeans.growingBeans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcGJkOVMpNJ4O-4g2JjSmtao9BUFhwLS8',
    appId: '1:594367967534:web:2480b49fadb2e5d1794abf',
    messagingSenderId: '594367967534',
    projectId: 'growing-beans-edu-tjwns',
    authDomain: 'growing-beans-edu-tjwns.firebaseapp.com',
    storageBucket: 'growing-beans-edu-tjwns.firebasestorage.app',
  );
}
